# Generated by Django 4.2.1 on 2023-05-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_voterecord_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterecord_only',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
